Revert "Update pycrypto to pycryptodome (closes TLP-657)"
This reverts commit e2b1662c7b9db56fc442c9b0ba6f6aceead6357e.
which was causing the error below. The problem was resolved by
reverting to the original dependency value.

2018] GET /login => generated 1113 bytes in 3 msecs (HTTP/1.0 302) 5 headers in 759 bytes (1 switches on core 0)
[2018-10-26 12:54:26,140] ERROR in app: Exception on /gCallback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 595, in callback
    user.refresh_token = token['refresh_token']
  File "./app.py", line 184, in refresh_token
    session['refresh_token'] = encrypt(value, iv)
  File "./utils.py", line 44, in encrypt
    return cipher.encrypt(value)
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_cfb.py", line 158, in encrypt
    c_uint8_ptr(plaintext),
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <type 'unicode'> cannot be passed to C code